version: '3.3'
services:

  home-assistant:
    image: homeassistant/raspberrypi3-homeassistant:stable
    volumes:
     - ${PWD}/config:/config
     - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: "host"
    environment:
    - TZ=America/New_York
